# don't forget to install the dependencies! >.>
# NOTE: this is a template, i'll make it autogenerate from the *.py file itself soon:tm:

[general]
# Please visit https://discord.com/developers first to create a new app,
# then copy the Application ID here
client_id = 1312804959116329003
# Specifies the RPC update interval, default is 5
# Discord usually rate-limits the RPC itself at around 5 seconds
update_interval = 5
# this is used if the script can't detect currently focused window,
# or no window is focused
idle_message = staring at the void >.> (Taskbar)
# Whether to enable Window Title Detection or not
# NOTE: this will not prevent the AFK Detection from running [TODO]
window_title_detection_enabled = true
# Use alternative details
# NOTE: the separate placeholders are not developed yet [TODO],
# as soon as this exists, you can just remove it from details config instead
fallback_details = Foreground program detection is disabled!

[censor_map]
# Changes the order of methods, also ensures that you censor the right thing
# NOTE: there are custom formats, which is explained on their own sub
rule_order = full_replace, word_replace, pattern_replace
# This method replaces everything that is sent to the "details"
full_replace = 
    @gmail.com = IRL stuff is on foreground!
    Layar Penguncian Default Windows = Windows Default Lock Screen
    Program Manager = Desktop (Home screen / Program Manager)
# This method replaces part of the titlebar
word_replace = 
    dingus = chungus
# This method replaces based on the regex arguments
# (google it for more information about regex)
pattern_replace = 
    @.* - Discord = @DMs - Discord
    ^YouTube - = <empty>
# Apply RegEx directly from the raw titlebar before any methods
# NOTE: this clutters the script since we have the rule order already [TODO]
apply_pattern_on_raw = false

[large_time_ranges]
# Specifies time-based RPC assets
# This will change the Large Assets, which you can configure there
# If there is a time gap, it will fallback to default
# NOTE: instead of fixed morning/afternoon/evening/night,
# make it so user can customize the variable name [TODO]
morning_start = 5
morning_end = 12
afternoon_start = 12
afternoon_end = 16
evening_start = 16
evening_end = 22
night_start = 22
night_end = 5

[small_time_ranges]
# Specifies time-based RPC assets
# This will change the Small Assets, which you can configure there
# If there is a time gap, it will fallback to default
# NOTE: instead of fixed morning/afternoon/evening/night,
# make it so user can customize the variable name [TODO]
morning_start = 5
morning_end = 12
afternoon_start = 12
afternoon_end = 16
evening_start = 16
evening_end = 22
night_start = 22
night_end = 5

[large_assets]
# Specifies the text shown on large image hover
morning_text = morning
afternoon_text = afternoon
evening_text = evening
night_text = night
default_text = You haven't set the time yet!
# Specifies the image assets, this must match to the
# one you submitted on Discord Developer Portal
morning_image = morning
afternoon_image = afternoon
evening_image = evening
night_image = night
default_image = notime

[small_assets]
# Specifies the text shown on small image hover
morning_text = morning
afternoon_text = afternoon
evening_text = evening
night_text = night
default_text = You haven't set the time yet!
# Specifies the image assets, this must match to the
# one you submitted on Discord Developer Portal
morning_image = online
afternoon_image = online
evening_image = idle
night_image = idle
default_image = notime

[layout]
# NOTE: this implementation is not finished yet [TODO]
show_large_image = true
show_small_image = true
show_buttons = true
details_field = true
state_field = true

[buttons]
# NOTE: there are custom formats, you can use:
# <time> for time on your computer
# <percentage> for battery percentage
# <plug> for on battery / charging state
# <remaining> for estimated time remaining (on battery only)
button_1_label = <time>, <percentage> <plug><remaining>
button_1_url = https://time.is/GMT+7
button_2_label = don't know what to put here T_T
button_2_url = https://google.com

[afk]
# Specifies the amount of time before the RPC treats as AFK
# NOTE: this RPC was designed for time-based in mind,
# there is currently no option that can disable this,
# but setting it to 0 will always treats as AFK [TODO]
idle_threshold = 60
# Specifies the AFK message that will be send to "details"
afk_message = User is suspected to be AFK
# Specifies the AFK small image, this will
# override any small image that currently set
afk_image = zzz
# Whether to show idle text on small image hover
show_idle_time = true
# NOTE: there are custom formats, you can use:
# <hours> for hours
# <minutes> for minutes
# <seconds> for seconds
idle_text = since <hours>h <minutes>m <seconds>s

[messages]
# Customizes supported message that appears on Windows notifications
# NOTE: IIRC, there is another one that sent a push on error, 
# make it customizable as well [TODO]
rpc_restarted_message = Rich Presence has been restarted (report a bug if it loops)

[gui]
# =============== COMMENTS ===============
# TODO from the GUI itself:
# * Make the GUI have a scrollbar, it's not small-resolution friendly without it
# * Add a (*) indicator just like notepad, if there is unsaved changes
# * Add a Delete confirmation on list
# * Reload RPC button itself is a stub, make it real
#   (IIRC, the main code doesn't even have the graceful reload handler)
# * Do not make the commands as menubar (Save, Reload config, Reload RPC, etc.)
# * After all of this is done, make the GUI itself configurable, like:
#   - Customize shortcuts (currently, it's only for Save command)
#   - etc.
fallback_details = text
# =============== CENSOR MAP ===============
rule_order = text
full_replace = list
word_replace = list
pattern_replace = list
apply_pattern_on_raw = bool
# =============== TIME RANGES ===============
morning_start = number
morning_end = number
afternoon_start = number
afternoon_end = number
evening_start = number
evening_end = number
night_start = number
night_end = number
# =============== LARGE ASSETS ===============
morning_text = text
afternoon_text = text
evening_text = text
night_text = text
default_text = text
morning_image = text
afternoon_image = text
evening_image = text
night_image = text
default_image = text
# =============== SMALL ASSETS ===============
small_assets.morning_text = text
small_assets.afternoon_text = text
small_assets.evening_text = text
small_assets.night_text = text
small_assets.default_text = text
small_assets.morning_image = text
small_assets.afternoon_image = text
small_assets.evening_image = text
small_assets.night_image = text
small_assets.default_image = text
# =============== LAYOUT ===============
show_large_image = bool
show_small_image = bool
show_buttons = bool
details_field = bool
state_field = bool
# =============== BUTTONS ===============
button_1_label = text
button_1_url = text
button_2_label = text
button_2_url = text
# =============== AFK ===============
idle_threshold = number
afk_message = text
afk_image = text
show_idle_time = bool
idle_text = text
# =============== MESSAGES ===============
rpc_restarted_message = text
# =============== GUI-SPECIFIC SETTINGS ===============
save_shortcut = <Control-s>
exit_shortcut = <Control-q>
reload_shortcut = <Control-r>
